### ISSUE TITLE
plugin doesn't start when teleinfo not enabled on remora

### ISSUE THREAD

**Issue by KipK** [FreeTHX/remora-ha#5]
plugins fails when fetching http://remora.local/tinfo as this endpoint answer "teleinfo not enabled"  when disabled on Remora.

`Traceback (most recent call last):
  File "/config/custom_components/remora/__init__.py", line 35, in async_setup
    await remora.async_updateTeleInfo()
  File "/config/custom_components/remora/remora.py", line 41, in async_updateTeleInfo
    self._teleInfo = await self.async_get_TeleInfo()
  File "/config/custom_components/remora/remora.py", line 36, in async_get_TeleInfo
    return await self._remora.getTeleInfo()
  File "/usr/local/lib/python3.10/site-packages/remora/remora.py", line 40, in getTeleInfo
    return (await tinfo.json())
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('http://remora.local/tinfo')`

**Comment by FreeTHX** [comment]
Hi @KipK 
Indeed, teleinfo is not mandatory on remora and as is should not be forced
Quick fix : comment line [35](https://github.com/FreeTHX/remora-ha/blob/6844c293fd666d399fc3850a3e3105c71b4f3626/custom_components/remora/__init__.py#L35) to remove the teleinfo on testing

On my side, I will : 
- add a test / heartbeat in the python remora library (documented [here](https://github.com/hallard/remora_soft/blob/66aad03b3634ba5932d9999fb52ba46963e31d37/remora_soft.ino#L640))
- update the testing on the home assistant component

**Comment by FreeTHX** [comment]
Hi @KipK 

I finaly update the [pyremora](https://github.com/FreeTHX/pyremora/commit/8e2b7e8b2b81964bf376e3c13cff17596ce59e55) lib.
This should have fix this issue.
Could you please confirm ?

**Comment by KipK** [comment]
does downloading the hass plugin again will update the library  ?

**Comment by KipK** [comment]
new errors here : 

Failure while testing Remora device.
```
Logger: custom_components.remora
Source: custom_components/remora/remora.py:59
Integration: remora ([documentation](https://github.com/FreeTHX/remora-ha/blob/master/README.md))
First occurred: 14:50:35 (1 occurrences)
Last logged: 14:50:35

Failure while testing Remora device.
Traceback (most recent call last):
  File "/config/custom_components/remora/__init__.py", line 40, in async_setup
    await remora.async_updateAllFilPilote()
  File "/config/custom_components/remora/remora.py", line 64, in async_updateAllFilPilote
    self._filPiloteDic = await self.async_get_AllFilPilote()
  File "/config/custom_components/remora/remora.py", line 59, in async_get_AllFilPilote
    return await self._remora.getAllFilPilote()
  File "/usr/local/lib/python3.10/site-packages/remora/remora.py", line 71, in getAllFilPilote
    async with aiohttp.request('GET', self.baseurl + 'fp') as fp:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1189, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

ma config:

`remora:
  host: '192.168.46.20'
climate:
  - platform: remora
    filpilote:
      - fp: 1
        name: 'Radiateur Couloir'
      - fp: 2
        name: 'Radiateur Salon'
      - fp: 3
        name: 'Radiateur Boudoir'
      - fp: 4
        name: 'Radiateur Chambre'
      - fp: 5
        name: 'Radiateur Studio'
      - fp: 6
        name: 'Radiateur Etage'
      - fp: 7
        name: 'Fil Pilote Unused'
    relais: False`

**Comment by KipK** [comment]
I had no time to give a look to the code and the requested endpoints yet. Sorry for the miss of informations here. I'm testing Hass to see if it worth switching from Jeedom someday

**Comment by KipK** [comment]
ok j'ai trouvé il faut qd meme renseigner un sensor: dans la conf sinon ca plante

**Comment by FreeTHX** [comment]
Si la teleinfo n'est pas active, ceci ne fait pas de sens.
Je corrige également ce bug

**Comment by KipK** [comment]
Autre chose que j'ai noté, mais ca vient peut etre du fait que je ne connais pas encore bien hass, les fils pilotes apparaissent comme entities, mais n'ont pas d'appareil associé.
Du coup on ne peut pas simplement les utiliser dans une action d'automatisation ( ca ne liste que les appareils, pas les properties ) 

edit: noob fail. ok j'ai trouvé ca apparait dans service. Difficile encore de retrouver mes petits tellement je suis habitué à Jeedom.
